PACKAGE_NAME = "SConsArchives"
 
env = Environment(tools=['default','scala']) 
env.Append(SCALACLASSPATH = ['/usr/share/java/scala-swing.jar'],
           SCALACLASSDIR = ['/usr/share/java/scala-swing.jar'])

classes = env.Scala('classes', 'src/SConsArchives.scala')
print map(str, classes)
class_files = Glob("classes/*.class")
jar = env.Jar(PACKAGE_NAME, class_files + ["MANIFEST"], JARCHDIR='classes')
env.Depends(jar, classes)

env.Clean(jar, class_files)

