import glob

PACKAGE_NAME = "SConsArchives"
 
env = Environment(JAVAC = "scalac", 
                  JAVASUFFIX=".scala",
                  JAVACLASSPATH = "/usr/share/java/scala-swing.jar",
                  JAVACLASSDIR = "/usr/share/java/scala-swing.jar")

classes = env.Java('classes', 'src', JAVAVERSION='scala')
class_files = Glob("classes/*.class")
jar = env.Jar(PACKAGE_NAME, class_files + ["MANIFEST"])
env.Depends(jar, classes)

env.Clean(jar, class_files)

